### ISSUE TITLE
How to include a website without iConnect lib

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#2]
@bogdandinchev 

We need to include the third-party sites in AIW Browser Platform. You can use https://bluemetrics.com.br/ as an example.

**Comment by bogdandinchev** [comment]
@pedro-young-wedbush 

The reason why some third party websites can't load is because of Content-Security-Policy. A site can set its 'frame-ancestors' directive to 'self' and only known domains, which fodbids it to be embedded in other places (including our windows in the workspace). Unfortunately... not much can be done about that.

There is a plan to bypass this with a browser extention a few months in the future (but still it is not a 100% reliable option, because there are other mechanism that can prevent embedding). For now you will have to check which sites can/can't be embedded manually.

For example - https://bluemetrics.com.br/  allows itself to be embedded, but google/cnn/linkedin for example don't

**Comment by pedro-young-wedbush** [comment]
Is there a way to set third-party apps to open in a new browser tab as an alternative?

**Comment by bogdandinchev** [comment]
I have updated the master branch with an example for opening an external app as a new window in the custom section:
https://github.com/InteropIO/wedbush-io-browser/commit/6cadd5b4d8429fc233a0535bdaff6b10fe3a316a

You can read more on window management in the docs here: https://docs.interop.io/browser/capabilities/windows/window-management/index.html#overview

In the default section there is a menu on each item, which gives the option to open in a new window: [cid:ba6bba33-8fea-4947-a41f-891741e82d8c]

Regards,


[cid:4700b394-144b-4346-b728-5a8c411d1605]





Bogdan Dinchev



Consultant

***@***.***

________________________________

**Comment by bogdandinchev** [comment]
We can use the browser api to open the window in a new tab:

https://github.com/InteropIO/wedbush-io-browser/commit/308bacad6aff5b1a0be61d70703a6e1a776eb6ab


[cid:f9d6f8c6-6fa4-406d-8a52-0e8d74d7cd66]





Bogdan Dinchev



Consultant

***@***.***

________________________________

**Comment by pedro-young-wedbush** [comment]
@bogdandinchev and @gganchev73 - Thank you for your advice!

We are able to handle these two use cases with third parties:
1. A site allows the iFrame integration: It opens as an application tab inside the workspace.
2. A site does not allow the iFrame integration. It opens as a separate browser tab.  Please let u know if there are plans in place to improve this user experience. 

Best,
Pedro
