### ISSUE TITLE
Remove Interop.io Screen from the Landing Page

### ISSUE THREAD

**Issue by pedro-young-wedbush** [InteropIO/wedbush-io-browser#9]
@bogdandinchev @gganchev73 

How do we remove this screen

![image](https://github.com/user-attachments/assets/032c8a89-59db-4f4b-b9a6-ecf8ae6c1d64)

**Comment by bogdandinchev** [comment]
Hey Pedro,

This screen is called the 'setupFlow' . Its use is to make the user give the necessary browser permissions so that the platform can work correctly.
You can read more about it here - https://docs.interop.io/browser/capabilities/home-app/library-features/index.html#using_the_components-setup_flow

to disable the setup flow you can just do:
...
setupFlow: {
        enabled: false,
      },
...
it is a top-level key property of the IOConnectHomeConfig object. However probably it is a good idea to have such a screen if not the default a customized one - it shows only the first time and makes sure things runs smoothly.

Regards,


[cid:a17a0921-3d96-4b3b-838d-7f5880004451]





Bogdan Dinchev



Consultant

***@***.***

________________________________
From: pedro-young-wedbush ***@***.***>
Sent: Thursday, October 3, 2024 5:47 PM
To: InteropIO/wedbush-io-browser ***@***.***>
Cc: Bogdan Dinchev ***@***.***>; Mention ***@***.***>
Subject: [Ext] [InteropIO/wedbush-io-browser] Remove Interop.io Screen from the Landing Page (Issue #9)


@bogdandinchev<https://github.com/bogdandinchev> @gganchev73<https://github.com/gganchev73>

How do we remove this screen

image.png (view on web)<https://github.com/user-attachments/assets/032c8a89-59db-4f4b-b9a6-ecf8ae6c1d64>

**Comment by pedro-young-wedbush** [comment]
@bogdandinchev

Why is it a good idea to show this screen? Also, how do we customize and brand the screen?

Pedro

**Comment by bogdandinchev** [comment]
Essentially you need to grant the browser permissions, which allow all functionalities of io.CB and it will work correctly.
The window management permission allows the ability to drag/drop windows in Workspace, extract windows from workspace, etc.
The notifications permission allows the ability to use notifications

At the moment you can only customize the logo or disable the setupFlow. You can also implement your own setup flow and render the HomeUI component after the permissions have been given (similarly to how you would implement a custom auth screen).

Do you have any specific requests for the customization point - we can possibly add this as a feature in a future version.

**Comment by pedro-young-wedbush** [comment]
@bogdandinchev, 

From an end user's perspective, we need to provide a business justification in a language free of technical jargon and aligned with our branding. 

Nowadays, online users are sensitive to granting permissions.

**Comment by bogdandinchev** [comment]
Okay from a users perspective:
If you don't plan to use notifications - than the notifications permission is not required. If you want to use them - without the permission notifications will be blocked by the browser and you can't use them.

If you want to keep track of multiple windows and restore a layout (keeping the position of each window) than you need 'windows management' permission given. If you don't provide the permission - the layouts tab would be hidden, if you tty to restore a layout through the api - the apps will all be restored in the default frame and not how the user would expect.

So if you are planning to use 'layouts' functionality you should enable the permission, if not - permission not necessary.

Let me know if more info is required.
